
FROM hello_flask:base

# ---------------------------
# Things all Developers need
# ---------------------------

COPY requirements-dev.txt $DEPLOY_DIR

RUN pip install -r requirements-dev.txt

EXPOSE 5000/tcp

# --------------------------
# Developer-specific setup
# --------------------------

RUN apk add screen

COPY .profile .ashrc .ash_aliases /root/

# ash options
#   -l login shell
#   -i interactive
CMD ["/bin/ash", "-l", "-i"]


# docker run command (IP unknown)
# docker run -it -p 5000:5000 hello_flask:dev

# docker run (known IP)
# docker run -it --ip 172.17.0.2 -p 5000:5000  hello_flask:dev

# binding source code
# docker run -it -p 5000:5000 --mount type=bind,src=~/Projects/docker-practice/dockerfile3_flask_page,dst=/opt/hello_flask/ hello_flask:dev


# Run app w/ these options (I'm not sure if IP will be the same)
# flask --app hello_flask run --host 172.17.0.2 --port 5000 --debug