
FROM python:3.14.2-alpine3.23

LABEL description="hello_flask app"

ENV DEPLOY_DIR=/opt/hello_flask/

COPY hello_flask.py requirements.txt $DEPLOY_DIR

WORKDIR $DEPLOY_DIR

RUN pip install -r requirements.txt
