# This will create a generic Ubuntu container that I will start a shell on
# in order to find out why I wasn't able to install python in the images
# (it might already be installed)
FROM ubuntu:latest

# build with the following command
# docker build -t my_ubuntu_image .